### ISSUE TITLE
Editor world size should be 480X800

### ISSUE THREAD

**Issue by sherifkandeel** [SteveDunn/Gleed2D#14] opened 2012-01-30 01:43 UTC
isn't the world size should be 480X800 to match a wp7 game ?

how can I alter that from the source code to match my needs ?

**Comment by SteveDunn** [comment] 2012-01-30 12:20
Hi,
The 'world size' is entirely up to you.  The 'view size' is 480x800 in the
WP7.  You shouldn't need to change any Gleed2D related code.

Cheers,

Steve

On 30 January 2012 01:43, sherifkandeel <
reply@reply.github.com

**Comment by sherifkandeel** [comment] 2012-01-30 13:35
How come? The position in the view is centered, when I created some textures their position property were either in negative or larger than 480 or 800
There were completely irrrelevant to the WP screen size

Sent from my Kindle Fire

**Comment by SteveDunn** [comment] 2012-01-30 13:57
There are no boundaries in the editor.  You can have 1 object at 0,0 and
one object 123456789,99999999
Re. negative numbers: again, that's how draw them in the editor.  There's
no boundaries and by default, the centre of the canvas is at 0,0 (not the
top left).
Hope this helps.

Cheers,

Steve.

On 30 January 2012 13:35, sherifkandeel <
reply@reply.github.com

**Comment by SteveDunn** [comment] 2012-01-31 17:09
Hope this info helps.  I'll close this as it's not a bug, but drop me a line if I can help any more

**Closed as completed by SteveDunn** 2012-01-31 17:09 UTC
Labels: feature

**Comment by sherifkandeel** [comment] 2012-01-31 21:05
yeah, this was helpful thankyou,
though I made my own hack for that, I drew a rectangle with dimensions
800X480 and position set to 0,0
so that I can design the level inside it, then export it to the .gleed file
and load it successfully.
